#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_RM6D010)	+=  raydium_driver.o raydium_sysfs.o raydium_fw_update.o

