# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_QRTR) := qrtr.o ns.o

obj-$(CONFIG_QRTR_SMD) += qrtr-smd.o
qrtr-smd-y	:= smd.o
obj-$(CONFIG_QRTR_TUN) += qrtr-tun.o
qrtr-tun-y	:= tun.o
obj-$(CONFIG_QRTR_MHI) += qrtr-mhi.o
qrtr-mhi-y	:= mhi.o
obj-$(CONFIG_QRTR_HAVEN) += qrtr-haven.o
qrtr-haven-y	:= haven.o
obj-$(CONFIG_QRTR_ETHERNET) += qrtr-ethernet.o
qrtr-ethernet-y	:= ethernet.o
obj-$(CONFIG_QRTR_MHI_DEV) += qrtr-mhi-dev.o
qrtr-mhi-dev-y	:= mhi_dev.o
obj-$(CONFIG_QRTR_BPF_FILTER) += qrtr-bpf_service.o
qrtr-bpf_service-y	:= bpf_service.o
obj-$(CONFIG_QRTR_USB_DEV) += qrtr-usb-dev.o
qrtr-usb-dev-y	:= usb_dev.o

